services:

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - uptime-kuma:/app/data

  kuma-relay:
    build:
      context: .
    image: wongbp/uptime-kuma-relay:latest
    container_name: kuma-relay
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    mem_limit: 200m
    cpus: 1
    volumes:
      - ./config.json:/app/config.json:ro

    depends_on:
      - uptime-kuma


volumes:
  uptime-kuma:
